<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:cinclude="http://apache.org/cocoon/include/1.0"
  xmlns:dir="http://apache.org/cocoon/directory/2.0"
  xmlns:sql="http://apache.org/cocoon/SQL/2.0"
  xmlns:email="http://apache.org/cocoon/transformation/sendmail">
  <!-- -->
  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:param name="timestamp"/>
  <xsl:param name="sender"/>
  <xsl:param name="server"/>          
  <xsl:param name="recipient"/>
  <xsl:param name="mv_count"/>  
  <!--  -->    
  <xsl:template match="node()|@*">
    <xsl:copy copy-namespaces="no">
      <xsl:apply-templates select="node()|@*"/>
    </xsl:copy>
  </xsl:template>        
  <!-- -->
  <xsl:template match="entry">   
   <xsl:copy>
    <xsl:choose>          
      <xsl:when test="count(sql:rowset/sql:row) != number($mv_count) or sql:rowset/sql:row/sql:compile_state != 'VALID' or sql:rowset/sql:row/sql:refresh_status != 'OK' ">
          <warning>Problems exist with MVs</warning>
          <email:sendmail>
            <email:from><xsl:value-of select="$sender"/></email:from>
            <email:to><xsl:value-of select="$recipient"/></email:to>
            <!--email:to><xsl:value-of select="'addanotherrecipienthere@philips.com'"/></email:to-->
            <email:subject><xsl:value-of select="concat('Warning: Problems exist with materialized views (instance:',substring-before(substring-after($server,'http://'),':'),'). Autogenerated email sent at ',$timestamp,' by Pika Chu')"/></email:subject>                        
            <email:body mime-type="text/plain">                                
Potential problems exist with materialized views:
================================================
<xsl:text>
</xsl:text>
<xsl:if test="count(sql:rowset/sql:row) != number($mv_count)">
Expected count: <xsl:value-of select="$mv_count"/>
Actual count: <xsl:value-of select="count(sql:rowset/sql:row)"/>
</xsl:if>
<xsl:if test="sql:rowset/sql:row[sql:compile_state!='VALID']">
  <xsl:for-each select="sql:rowset/sql:row[sql:compile_state!='VALID']">
<xsl:text>Invalid MV:          </xsl:text><xsl:value-of select="sql:mview_name"/><xsl:text>
</xsl:text>
  </xsl:for-each>
</xsl:if>
<xsl:if test="sql:rowset/sql:row[sql:refresh_status!='OK']">
  <xsl:for-each select="sql:rowset/sql:row[sql:compile_state!='VALID']">
<xsl:text>Stale MV:          </xsl:text><xsl:value-of select="sql:mview_name"/><xsl:text>
</xsl:text>
  </xsl:for-each>
</xsl:if>
</email:body>
        </email:sendmail>    
      </xsl:when>   
      <xsl:otherwise>
        <result>OK</result>
        <xsl:apply-templates select="node()|@*"/>
      </xsl:otherwise>        
    </xsl:choose>    
    </xsl:copy>
  </xsl:template>
</xsl:stylesheet>
