<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:cinclude="http://apache.org/cocoon/include/1.0"
  xmlns:dir="http://apache.org/cocoon/directory/2.0"
  xmlns:sql="http://apache.org/cocoon/SQL/2.0"
  xmlns:email="http://apache.org/cocoon/transformation/sendmail">
  <!-- -->
  <xsl:param name="timestamp"/>
  <xsl:param name="sender"/>
  <xsl:param name="server"/>
  <xsl:param name="recipient"/>
  <xsl:param name="deletionsthreshold"/>  
  <xsl:param name="deletionscount"/>
  <xsl:param name="customer_id"/>
  
  <!--  -->
  <xsl:template match="/root">
    <root>
      <warning>catalog_definition: Number of inferred deletions exceeds threshold for <xsl:value-of select="$customer_id"/></warning>
      <email:sendmail>
        <email:from><xsl:value-of select="$sender"/></email:from>
        <email:to><xsl:value-of select="$recipient"/></email:to>
        <email:subject><xsl:value-of select="concat('catalog_definition: Number of inferred deletions exceeds threshold (instance:',substring-before(substring-after($server,'http://'),':'),'). Autogenerated email sent at ',$timestamp,' by Pika Chu')"/></email:subject>
        <email:body mime-type="text/plain">
Too many inferred deletions for <xsl:value-of select="$customer_id"/>

   - threshold: <xsl:value-of select="$deletionsthreshold"/>
   - inferred deletions: <xsl:value-of select="$deletionscount"/>

</email:body>
      </email:sendmail>
    </root>
  </xsl:template>
</xsl:stylesheet>
