<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:variable name="docTypes">
		<ResourceType>_FB</ResourceType>
		<ResourceType>_FG</ResourceType>
		<ResourceType>_FM</ResourceType>
		<ResourceType>_FS</ResourceType>
		<ResourceType>_FV</ResourceType>
		<ResourceType>_FW</ResourceType>
		<ResourceType>ABS</ResourceType>
		<ResourceType>ABV</ResourceType>
		<ResourceType>AEC</ResourceType>
		<ResourceType>AP1</ResourceType>
		<ResourceType>AP2</ResourceType>
		<ResourceType>APV</ResourceType>
		<ResourceType>BLL</ResourceType>
		<ResourceType>BLM</ResourceType>
		<ResourceType>BLS</ResourceType>
		<ResourceType>BRW</ResourceType>
		<ResourceType>CLL</ResourceType>
		<ResourceType>CLM</ResourceType>
		<ResourceType>CLS</ResourceType>
		<ResourceType>COL</ResourceType>
		<ResourceType>COW</ResourceType>
		<ResourceType>D1S</ResourceType>
		<ResourceType>D1V</ResourceType>
		<ResourceType>D2S</ResourceType>
		<ResourceType>D2V</ResourceType>
		<ResourceType>D3S</ResourceType>
		<ResourceType>D3V</ResourceType>
		<ResourceType>D4S</ResourceType>
		<ResourceType>D4V</ResourceType>
		<ResourceType>DFU</ResourceType>
		<ResourceType>DPS</ResourceType>
		<ResourceType>DPV</ResourceType>
		<ResourceType>DPW</ResourceType>
		<ResourceType>FDF</ResourceType>
		<ResourceType>FDM</ResourceType>
		<ResourceType>FDS</ResourceType>
		<ResourceType>FDT</ResourceType>
		<ResourceType>FIH</ResourceType>
		<ResourceType>FIS</ResourceType>
		<ResourceType>FIW</ResourceType>
		<ResourceType>FLM</ResourceType>
		<ResourceType>FLS</ResourceType>
		<ResourceType>FLW</ResourceType>
		<ResourceType>FML</ResourceType>
		<ResourceType>FMM</ResourceType>
		<ResourceType>FMS</ResourceType>
		<ResourceType>FMT</ResourceType>
		<ResourceType>FTS</ResourceType>
		<ResourceType>FTV</ResourceType>
		<ResourceType>MCW</ResourceType>
		<ResourceType>P3D</ResourceType>
		<ResourceType>PA3</ResourceType>
		<ResourceType>PA4</ResourceType>
		<ResourceType>PAV</ResourceType>
		<ResourceType>PIS</ResourceType>
		<ResourceType>PLW</ResourceType>
		<ResourceType>PP1</ResourceType>
		<ResourceType>PRD</ResourceType>
		<ResourceType>PRM</ResourceType>
		<ResourceType>PRV</ResourceType>
		<ResourceType>PSS</ResourceType>
		<ResourceType>PWB</ResourceType>
		<ResourceType>PWF</ResourceType>
		<ResourceType>PWM</ResourceType>
		<ResourceType>PWS</ResourceType>
		<ResourceType>PWV</ResourceType>
		<ResourceType>PWW</ResourceType>
		<ResourceType>QIG</ResourceType>
		<ResourceType>QSG</ResourceType>
		<ResourceType>RCS</ResourceType>
		<ResourceType>RCV</ResourceType>
		<ResourceType>RTS</ResourceType>
		<ResourceType>RTV</ResourceType>
		<ResourceType>SLW</ResourceType>
		<ResourceType>TLS</ResourceType>
		<ResourceType>TLV</ResourceType>
		<ResourceType>TNT</ResourceType>
		<ResourceType>TRS</ResourceType>
		<ResourceType>TRV</ResourceType>
		<ResourceType>TS1</ResourceType>
		<ResourceType>TS2</ResourceType>
		<ResourceType>TSV</ResourceType>
		<ResourceType>U1S</ResourceType>
		<ResourceType>U1V</ResourceType>
		<ResourceType>U2S</ResourceType>
		<ResourceType>U2V</ResourceType>
		<ResourceType>UPS</ResourceType>
		<ResourceType>UPV</ResourceType>
		<ResourceType>UWM</ResourceType>
		<ResourceType>UWS</ResourceType>
		<ResourceType>UWV</ResourceType>
		<ResourceType>UWW</ResourceType>
		<ResourceType>PMT</ResourceType>
		<ResourceType>PDT</ResourceType>
		<ResourceType>PMB</ResourceType>
		<ResourceType>PDB</ResourceType>
	</xsl:variable>
</xsl:stylesheet>
