exec dbms_stats.gather_schema_stats('CMC2_PROD1_SCHEMA');
analyze table CATALOG_CTL compute statistics;
analyze table CATALOG_OBJECTS compute statistics;
analyze table CATEGORIZATION compute statistics;
analyze table CONTENT_TYPES compute statistics;
analyze table CTL compute statistics;
analyze table CTL_RELATIONS compute statistics;
analyze table LANGUAGE_TRANSLATIONS compute statistics;
analyze table LOCALE_LANGUAGE compute statistics;
analyze table LOCALIZED_SUBCAT compute statistics;
analyze table OBJECT_CATEGORIZATION compute statistics;
analyze table OBJECT_MASTER_DATA compute statistics;
analyze table OCTL compute statistics;
analyze table OCTL_RELATIONS compute statistics;
analyze table OCTL_STORE compute statistics;
