SET DEFINE OFF;
Insert into CTL
   (CONTENT_TYPE, LOCALISATION)
 Values
   ('catalog_configuration', 'none');
Insert into CTL
   (CONTENT_TYPE, LOCALISATION)
 Values
   ('catalog_definition', 'none');
Insert into CTL
   (CONTENT_TYPE, LOCALISATION)
 Values
   ('catalog_log', 'none');
Insert into CTL
   (CONTENT_TYPE, LOCALISATION)
 Values
   ('content_type_definition', 'none');
Insert into CTL
   (CONTENT_TYPE, LOCALISATION)
 Values
   ('content_type_log', 'none');
COMMIT;
