SET DEFINE OFF;
Insert into LOCALE_LANGUAGE  (LOCALE, CCR_LANGUAGE_CODE, CCR_LANGUAGE_NAME, LANGUAGECODE, COUNTRY_CODE, COUNTRY_NAME, COUNTRY, LANGUAGE)(
SELECT 'ar_AE','ARA','Arabic','ar_AE','AE','AE','AE','ARA' FROM DUAL UNION 
SELECT 'bg_BG','BUL','Bulgarian','bg_BG','BG','BG','BG','BUL' FROM DUAL UNION 
SELECT 'cs_CZ','CES','Czech','cs_CZ','CZ','CZ','CZ','CES' FROM DUAL UNION 
SELECT 'da_DK','DAN','Danish','da_DK','DK','DK','DK','DAN' FROM DUAL UNION 
SELECT 'de_AT','DEU','German','de_DE','AT','AT','AT','DEU' FROM DUAL UNION 
SELECT 'de_CH','DEU','German','de_DE','CH','CH','CH','DEU' FROM DUAL UNION 
SELECT 'de_DE','DEU','German','de_DE','DE','DE','DE','DEU' FROM DUAL UNION 
SELECT 'el_GR','ELL','Greek Modern','el_GR','GR','GR','GR','ELL' FROM DUAL UNION 
SELECT 'en_AU','AEN','English (US)','en_AU','AU','AU','AU','AEN' FROM DUAL UNION 
SELECT 'en_CA','AEN','English (US)','en_CA','CA','CA','CA','AEN' FROM DUAL UNION 
SELECT 'en_GB','ENG','English (UK)','en_GB','GB','GB','GB','ENG' FROM DUAL UNION 
SELECT 'en_HK','AEN','English (US)','en_HK','HK','HK','HK','AEN' FROM DUAL UNION 
SELECT 'en_IE','ENG','English (UK)','en_GB','IE','IE','IE','ENG' FROM DUAL UNION 
SELECT 'en_IN','AEN','English (US)','en_IN','IN','IN','IN','AEN' FROM DUAL UNION 
SELECT 'en_MY','AEN','English (US)','en_MY','MY','MY','MY','AEN' FROM DUAL UNION 
SELECT 'en_NZ','AEN','English (US)','en_NZ','NZ','NZ','NZ','AEN' FROM DUAL UNION 
SELECT 'en_PH','AEN','English (US)','en_PH','PH','PH','PH','AEN' FROM DUAL UNION 
SELECT 'en_PK','AEN','English (US)','en_PK','PK','PK','PK','AEN' FROM DUAL UNION 
SELECT 'en_SA','AEN','English (US)','en_SA','SA','SA','SA','AEN' FROM DUAL UNION 
SELECT 'en_SG','AEN','English (US)','en_SG','SG','SG','SG','AEN' FROM DUAL UNION 
SELECT 'en_US','AEN','English (US)','en_US','US','US','US','AEN' FROM DUAL UNION 
SELECT 'en_ZA','AEN','English (US)','en_ZA','ZA','ZA','ZA','AEN' FROM DUAL UNION 
SELECT 'es_AR','ASP','Spanish (Argentina)','es_AR','AR','AR','AR','ASP' FROM DUAL UNION 
SELECT 'es_CL','LSP','Spanish (Latin)','es_MX','CL','CL','CL','LSP' FROM DUAL UNION 
SELECT 'es_CO','LSP','Spanish (Latin)','es_MX','CO','CO','CO','LSP' FROM DUAL UNION 
SELECT 'es_ES','ESP','Spanish','es_ES','ES','ES','ES','ESP' FROM DUAL UNION 
SELECT 'es_MX','LSP','Spanish (Latin)','es_MX','MX','MX','MX','LSP' FROM DUAL UNION 
SELECT 'es_PA','LSP','Spanish (Latin)','es_MX','PA','PA','PA','LSP' FROM DUAL UNION 
SELECT 'es_PE','LSP','Spanish (Latin)','es_MX','PE','PE','PE','LSP' FROM DUAL UNION 
SELECT 'es_UY','ASP','Spanish (Argentina)','es_AR','UY','UY','UY','ASP' FROM DUAL UNION 
SELECT 'es_VE','LSP','Spanish (Latin)','es_MX','VE','VE','VE','LSP' FROM DUAL UNION 
SELECT 'et_EE','EST','Estonian','et_EE','EE','EE','EE','EST' FROM DUAL UNION 
SELECT 'fa_IR','FAS','Farsi (Persian)','fa_IR','IR','IR','IR','FAS' FROM DUAL UNION 
SELECT 'fi_FI','FIN','Finnish','fi_FI','FI','FI','FI','FIN' FROM DUAL UNION 
SELECT 'fr_BE','FRA','French','fr_BE','BE','BE','BE','FRA' FROM DUAL UNION 
SELECT 'fr_CA','CFR','French (Canada)','fr_CA','CA','CA','CA','CFR' FROM DUAL UNION 
SELECT 'fr_CH','FRA','French','fr_FR','CH','CH','CH','FRA' FROM DUAL UNION 
SELECT 'fr_FR','FRA','French','fr_FR','FR','FR','FR','FRA' FROM DUAL UNION 
SELECT 'hr_HR','HRV','Croatian','hr_HR','HR','HR','HR','HRV' FROM DUAL UNION 
SELECT 'hu_HU','HUN','Hungarian','hu_HU','HU','HU','HU','HUN' FROM DUAL UNION 
SELECT 'id_ID','IND','Bahasha Indonesian','id_ID','ID','ID','ID','IND' FROM DUAL UNION 
SELECT 'it_IT','ITA','Italian','it_IT','IT','IT','IT','ITA' FROM DUAL UNION 
SELECT 'ja_JP','JPN','Japanese','ja_JP','JP','JP','JP','JPN' FROM DUAL UNION 
SELECT 'kk_KZ','KAZ','Kazakh','kk_KZ','KZ','KZ','KZ','KAZ' FROM DUAL UNION 
SELECT 'ko_KR','KOR','Korean','ko_KR','KR','KR','KR','KOR' FROM DUAL UNION 
SELECT 'lt_LT','LIT','Lithuanian','lt_LT','LT','LT','LT','LIT' FROM DUAL UNION 
SELECT 'lv_LV','LAV','Latvian','lv_LV','LV','LV','LV','LAV' FROM DUAL UNION 
SELECT 'ms_MY','MSA','Malay','ms_MY','MY','MY','MY','MSA' FROM DUAL UNION 
SELECT 'nl_BE','NLD','Dutch','nl_NL','BE','BE','BE','NLD' FROM DUAL UNION 
SELECT 'nl_NL','NLD','Dutch','nl_NL','NL','NL','NL','NLD' FROM DUAL UNION 
SELECT 'no_NO','NOR','Norwegian','no_NO','NO','NO','NO','NOR' FROM DUAL UNION 
SELECT 'pl_PL','POL','Polish','pl_PL','PL','PL','PL','POL' FROM DUAL UNION 
SELECT 'pt_BR','BRP','Portuguese (Brazil)','pt_BR','BR','BR','BR','BRP' FROM DUAL UNION 
SELECT 'pt_PT','POR','Portuguese','pt_PT','PT','PT','PT','POR' FROM DUAL UNION 
SELECT 'ro_RO','RON','Romanian','ro_RO','RO','RO','RO','RON' FROM DUAL UNION 
SELECT 'ru_RU','RUS','Russian','ru_RU','RU','RU','RU','RUS' FROM DUAL UNION 
SELECT 'ru_UA','RUS','Russian','ru_RU','UA','UA','UA','RUS' FROM DUAL UNION 
SELECT 'sk_SK','SLK','Slovak','sk_SK','SK','SK','SK','SLK' FROM DUAL UNION 
SELECT 'sl_SI','SLV','Slovenian','sl_SI','SI','SI','SI','SLV' FROM DUAL UNION 
SELECT 'sr_RS','SRP','Serbian','sr_RS','RS','RS','RS','SRP' FROM DUAL UNION 
SELECT 'sv_SE','SWE','Swedish','sv_SE','SE','SE','SE','SWE' FROM DUAL UNION 
SELECT 'th_TH','THA','Thai','th_TH','TH','TH','TH','THA' FROM DUAL UNION 
SELECT 'tr_TR','TUR','Turkish','tr_TR','TR','TR','TR','TUR' FROM DUAL UNION 
SELECT 'uk_UA','UKR','Ukrainian','uk_UA','UA','UA','UA','UKR' FROM DUAL UNION 
SELECT 'vi_VN','VIE','Vietnamese','vi_VN','VN','VN','VN','VIE' FROM DUAL UNION 
SELECT 'zh_CN','ZHT','Chinese Simplified','zh_CN','CN','CN','CN','ZHT' FROM DUAL UNION 
SELECT 'zh_HK','ZHS','Chinese Traditional','zh_HK','HK','HK','HK','ZHS' FROM DUAL UNION 
SELECT 'zh_TW','TZH','Chinese Traditional','zh_TW','TW','TW','TW','TZH' FROM DUAL );
COMMIT;
