<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:sql="http://apache.org/cocoon/SQL/2.0"
                xmlns:email="http://apache.org/cocoon/transformation/sendmail"
                >
  <!-- -->
  <xsl:param name="sender"/>
  <xsl:param name="recipient"/>
  <!-- -->
  <xsl:template match="root">   
      <email:sendmail>
         <email:from><xsl:value-of select="$sender"/></email:from>
         <email:to><xsl:value-of select="$recipient"/></email:to>
         <email:subject>Autogenerated Product Report sent by PikaChu </email:subject>                        
         <email:body mime-type="text/html">
             <xsl:apply-templates select="html" /> 
         </email:body>
      </email:sendmail>    
  </xsl:template>
  <!--  -->    
  <xsl:template match="node()|@*">
    <xsl:copy copy-namespaces="no">
      <xsl:apply-templates select="node()|@*"/>
    </xsl:copy>
  </xsl:template>        
  <!--  -->    
</xsl:stylesheet>
