<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:cinclude="http://apache.org/cocoon/include/1.0"
  xmlns:dir="http://apache.org/cocoon/directory/2.0"
  xmlns:sql="http://apache.org/cocoon/SQL/2.0"
  xmlns:email="http://apache.org/cocoon/transformation/sendmail">
  <!-- -->
  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:param name="timestamp"/>
  <xsl:param name="sender"/>
  <xsl:param name="server"/>          
  <xsl:param name="recipient"/>
  <!--  -->     
  <xsl:template match="root[@catalog!='']">   
    <integritycheck check="uncategorizedproducts">
    <xsl:variable name="catalog" select="@catalog"/>
      <xsl:choose>          
        <xsl:when test="sql:rowset/sql:row">
          <catalog catalogcode="{@catalog}">
            <uncategorized-products>
              <xsl:for-each select="sql:rowset/sql:row/sql:object_id">
                <ctn><xsl:value-of select="."/></ctn>
              </xsl:for-each>
            </uncategorized-products>
            <email:sendmail>
              <email:from><xsl:value-of select="$sender"/></email:from>
              <email:to><xsl:value-of select="$recipient"/></email:to>
              <email:subject><xsl:value-of select="concat('Warning: Products in ', $catalog, ' catalog not mapped to a subcategory in ', $catalog, ' categorization tree (instance:',substring-before(substring-after($server,'http://'),':'),'). Autogenerated email sent at ',$timestamp,' by Pika Chu')"/></email:subject>                        
              <email:body mime-type="text/plain">                                
The following are products (PMT_Raw, status !='PLACEHOLDER') unassigned into the MASTER categorization tree :
=============================================================================================================
Products: <xsl:text>
</xsl:text>
<xsl:for-each select="sql:rowset/sql:row">
<xsl:text>          </xsl:text><xsl:value-of select="."/><xsl:text>
</xsl:text>
</xsl:for-each><xsl:text>
</xsl:text>
</email:body>
            </email:sendmail>
          </catalog>          
        </xsl:when>   
        <xsl:otherwise>
          <catalog catalogcode="{@catalog}">
            <comment>No uncategorized products found for this catalog</comment>
          </catalog>      
        </xsl:otherwise>
      </xsl:choose>
    </integritycheck>    
  </xsl:template>
</xsl:stylesheet>