<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:cinclude="http://apache.org/cocoon/include/1.0"
  xmlns:dir="http://apache.org/cocoon/directory/2.0"
  xmlns:sql="http://apache.org/cocoon/SQL/2.0"
  xmlns:email="http://apache.org/cocoon/transformation/sendmail">
  <!-- -->
  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:param name="timestamp"/>
  <xsl:param name="sender"/>
  <xsl:param name="server"/>
  <xsl:param name="recipient"/>
  <!--  -->
  <xsl:template match="/root">
    <root>
      <xsl:apply-templates select="node()|@*"/>    
    </root>
  </xsl:template>
  <!-- -->
  <xsl:template match="node()|@*">
    <xsl:apply-templates select="node()|@*"/>
  </xsl:template>
  <!-- -->
  <xsl:template match="sql:rowset[@name='nullstatuscheck']">
    <integritycheck check="nullStatusCheck">
    <xsl:choose>
      <xsl:when test="sql:row">
        <statusCheck>
          <xsl:for-each select="sql:row">
            <localisation><xsl:value-of select="sql:localisation"/></localisation>
            <count><xsl:value-of select="sql:count"/></count>          
          </xsl:for-each>
        </statusCheck>
        <email:sendmail>
          <email:from><xsl:value-of select="$sender"/></email:from>
          <email:to><xsl:value-of select="$recipient"/></email:to>
          <email:subject><xsl:value-of select="concat('Warning: Null status OCTL rows found which have OCTL_STORE content (instance:',substring-before(substring-after($server,'http://'),':'),'). Autogenerated email sent at ',$timestamp,' by Pika Chu')"/></email:subject>
          <email:body mime-type="text/plain">
Rows have been found in OCTL with null status for which corresponding rows exist in OCTL_STORE :
================================================================================================
Localisation,Count: <xsl:text>
</xsl:text>
<xsl:for-each select="sql:row">
<xsl:value-of select="sql:localisation"/>,<xsl:value-of select="sql:count"/><xsl:text>
</xsl:text>
</xsl:for-each><xsl:text>
</xsl:text>
</email:body>
        </email:sendmail>
      </xsl:when>
      <xsl:otherwise>
        <comment>No null status OCTL/OCTL_STORE rows found</comment>
      </xsl:otherwise>
    </xsl:choose>
    </integritycheck>
  </xsl:template>
  <!-- -->
  <xsl:template match="sql:rowset[@name='nonnullstatuscheck']">
    <integritycheck check="nonnullStatusCheck">
    <xsl:choose>
      <xsl:when test="sql:row">
        <statusCheck>
          <xsl:for-each select="sql:row">
            <content_type><xsl:value-of select="sql:content_type"/></content_type>
            <localisation><xsl:value-of select="sql:localisation"/></localisation>
            <ctn><xsl:value-of select="sql:object_id"/></ctn>
          </xsl:for-each>
        </statusCheck>
        <email:sendmail>
          <email:from><xsl:value-of select="$sender"/></email:from>
          <email:to><xsl:value-of select="$recipient"/></email:to>
          <email:subject><xsl:value-of select="concat('Warning: Non-null status OCTL rows found which are missing OCTL_STORE content (instance:',substring-before(substring-after($server,'http://'),':'),'). Autogenerated email sent at ',$timestamp,' by Pika Chu')"/></email:subject>
          <email:body mime-type="text/plain">
Rows have been found in OCTL with non-null status for which no corresponding row exists in OCTL_STORE :
=====================================================================================================
Content type,Localisation,CTN: <xsl:text>
</xsl:text>
<xsl:for-each select="sql:row">
<xsl:value-of select="sql:content_type"/>,<xsl:value-of select="sql:localisation"/>,<xsl:value-of select="sql:object_id"/><xsl:text>
</xsl:text>
</xsl:for-each><xsl:text>
</xsl:text>
</email:body>
        </email:sendmail>
      </xsl:when>
      <xsl:otherwise>
        <comment>No non-null status OCTL/OCTL_STORE rows found</comment>
      </xsl:otherwise>
    </xsl:choose>
    </integritycheck>
  </xsl:template>  
</xsl:stylesheet>
