# FYP

## intro

i am working as business analyst for the Digital Content project.
I have been assigned the task to determine the impact of this project on the support and service organisation.
I would like to have a meeting with you in order to learn which applications are used by your part of the organisation and what information is required to make your work possible.
When is a meeting (in person at HTC/via Skype) possible for you? 

## FYP future

- search
- assets (downloaden)
- product information

toekomst

- toegang via code1 account & STEP access
- producten personal health (niet health systems)
- zoeken op product ids & types (adv. search; zoeken op specificaties)
- alleen approved workspace
- niet alle locales tegelijk
- view/read only (obv aangepast read-only account)


resultaat

- product information
- specifications
- asset view (public/internal)
- online catalog



FYP - verschillen in toegankeljkheid ik / sc user


 - wie gebruikt FYP? 
 - hoeveel users
 - hoe doet een gemiddelde call center gebruiker zijn werk (met FYP)

**doel**;  
inzichtelijk krijgen van (informatie) gebruik huidige FYP vs mogelijkheden toekomstige STEP "FYP" portal.
waar gaan we te kort komen/pijn hebben?


Product-accesoire relaties
pre-/successor products




FAQ's CCR/FYP zijn overgezet naar Salesforce.
Is in iedergeval op de way out



Udo 

JAnne van Herpt

expert in knowledge management systemen Support (salesforce knowledge management)

FAQ's niet meer vanuit OLEE/CCR, maar vanuit SAlesforce



Udo: service center documentatie!



Nico Minaerts PO Service)


AYS - CTN of chassis nummer (chassis kan mogelijk eruit)

FAQs (OLEE based) in AYS kunenn er uit en moeten owrden vervangen door FAQs uit Salesforce. Ditr is nog niet voorzien.



200 cojntact centers
200-300 aantal gebruikers, via intern netwerk of VPN

Iedereen in srvice maakt er regelmatig geburik van. Pm 300 service mensen. Mogelijk/zeker ook de marketing mensen




Sleep /respitory care products: niet in Salesforce, wel op de website --> huidig probleem.
Patrick van Nuland van op de hoogte.
Mogelijk omdat deze producten al in STEP zijn opgenomen en ihet interface naar Salesforce nog niet bestaat.




