<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:cinclude="http://apache.org/cocoon/include/1.0" xmlns:dir="http://apache.org/cocoon/directory/2.0" xmlns:email="http://apache.org/cocoon/transformation/sendmail">
	<xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:param name="process"/>
	<xsl:param name="timestamp"/>
	<xsl:param name="sender"/>
	<xsl:param name="server"/>
	<xsl:param name="recipient"/>
	<!--  -->
	<xsl:template match="/dir:directory">
		<root>
			<xsl:if test="dir:file/dir:xpath/read">
				<email:sendmail>
					<email:from>
						<xsl:value-of select="$sender"/>
					</email:from>
					<email:to>
						<xsl:value-of select="$recipient"/>
					</email:to>
					<email:subject>
						<xsl:value-of select="concat('Warning: Errors in ', $process,' job (instance:',substring-before(substring-after($server,'http://'),':'),') - autogenerated email sent at ',$timestamp,' by Pika Chu')"/>
					</email:subject>
					<email:body mime-type="text/plain">
       				 Asset retrieval errors were encountered during processing for assets identified by the following URLs (InternalResourceIdentifier): 
					<xsl:apply-templates/>
					</email:body>
				</email:sendmail>
			</xsl:if>
		</root>
	</xsl:template>
	<xsl:template match="node()|@*">
		<xsl:apply-templates/>
	</xsl:template>
	<xsl:template match="read">                     
            Product:  <xsl:value-of select="@CTN"/>
            Request URL:  <xsl:value-of select="substring-after(@request,'url=')"/>
	</xsl:template>
</xsl:stylesheet>
