<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:cinclude="http://apache.org/cocoon/include/1.0"
  xmlns:dir="http://apache.org/cocoon/directory/2.0"
  xmlns:sql="http://apache.org/cocoon/SQL/2.0"
  xmlns:email="http://apache.org/cocoon/transformation/sendmail">
  <!-- -->
  <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:param name="timestamp"/>
  <xsl:param name="sender"/>
  <xsl:param name="server"/>
  <xsl:param name="recipient"/>
  <!--  -->
  <xsl:template match="node()|@*">
    <xsl:copy copy-namespaces="no">
      <xsl:apply-templates select="node()|@*"/>
    </xsl:copy>
  </xsl:template>
  <!-- -->
  <xsl:template match="source">
   <xsl:copy>
      <warning>Problems exist with PMT_Refs xml feed</warning>
      <email:sendmail>
        <email:from><xsl:value-of select="$sender"/></email:from>
        <email:to><xsl:value-of select="$recipient"/></email:to>
        <email:subject><xsl:value-of select="concat('Warning: Problems with PMT_Refs xml feed  (instance:',substring-before(substring-after($server,'http://'),':'),'). Autogenerated email sent at ',$timestamp,' by Pika Chu')"/></email:subject>
        <email:body mime-type="text/plain">
Too many changed product references
=========================
<xsl:text>
See attached logfile.
</xsl:text>
</email:body>
<xsl:variable name="logfilename" select="tokenize(.,'/')[last()]"/>
<email:attachment name="{$logfilename}" mime-type="text/xml" url="{concat('cocoon:/file__',.)}"/>
        </email:sendmail>
    </xsl:copy>
  </xsl:template>
</xsl:stylesheet>
