create database link pika connect to COCOON_PIKAD1_SCHEMA  IDENTIFIED by  AMEHCS_1DAKIP_NOOCOC using 'PCHU1D';
drop synonym CATEGORY_TREE;
drop synonym CHANNEL_CATALOGS;
drop synonym CHANNEL_EXPORT;
drop synonym CHANNEL_PARAM;
drop synonym CHANNELS;
drop synonym CUSTOMER_LOCALE_EXPORT;
create synonym CATEGORY_TREE for cocoon_pikad1_schema.CATEGORY_TREE@pika;
create synonym CHANNEL_CATALOGS for cocoon_pikad1_schema.CHANNEL_CATALOGS@pika;
create synonym CHANNEL_EXPORT for cocoon_pikad1_schema.CHANNEL_EXPORT@pika;
create synonym CHANNEL_PARAM for cocoon_pikad1_schema.CHANNEL_PARAM@pika;
create synonym CHANNELS for cocoon_pikad1_schema.CHANNELS@pika;
create synonym CUSTOMER_LOCALE_EXPORT for cocoon_pikad1_schema.CUSTOMER_LOCALE_EXPORT@pika;
